import { Button, HorizontalBox, VerticalBox } from "std-widgets.slint";
import { I18n } from "i18n.slint";

export component QuickControls inherits Rectangle {
    in property <string> locale;
    in property <bool> recording;
    in property <bool> streaming;
    in property <int> view-mode;
    callback toggle-recording();
    callback toggle-streaming();
    callback set-view-mode(int);
    callback open-settings();
    property <bool> virtual-camera: false;

    height: 64px;
    background: rgb(39, 52, 73);
    border-radius: 5px;
    VerticalBox {
        padding: 4px;
        spacing: 3px;
        HorizontalBox {
            spacing: 4px;
            Button {
                text: streaming
                    ? I18n.text.stop_short
                    : I18n.text.stream_short;
                width: 68px;
                height: 26px;
                clicked => toggle-streaming();
            }
            Button {
                text: recording
                    ? I18n.text.stop_short
                    : I18n.text.record_short;
                width: 68px;
                height: 26px;
                clicked => toggle-recording();
            }
            Button {
                text: I18n.text.camera + " (unsupported)";
                width: 68px;
                height: 26px;
                enabled: false;
            }
        }
        HorizontalBox {
            spacing: 4px;
            Button {
                text: view-mode == 0
                    ? I18n.text.studio_mode
                    : I18n.text.preview_only;
                width: 134px;
                height: 26px;
                clicked => set-view-mode(view-mode == 0 ? 1 : 0);
            }
            Button {
                text: I18n.text.settings;
                width: 68px;
                height: 26px;
                clicked => open-settings();
            }
        }
    }
}
