[workspace]
members = [
    "crates/obs-rs-app",
    "crates/obs-rs-audio",
    "crates/obs-rs-audio-wasapi",
    "crates/obs-rs-builtins",
    "crates/obs-rs-capture",
    "crates/obs-rs-capture-macos",
    "crates/obs-rs-capture-windows",
    "crates/obs-rs-clock",
    "crates/obs-rs-config",
    "crates/obs-rs-core",
    "crates/obs-rs-diagnostics",
    "crates/obs-rs-engine",
    "crates/obs-rs-gui",
    "crates/obs-rs-audio-pipewire",
    "crates/obs-rs-benchmark",
    "crates/obs-rs-media",
    "crates/obs-rs-output",
    "crates/obs-rs-output-gstreamer",
    "crates/obs-rs-plugin-api",
    "crates/obs-rs-project",
    "crates/obs-rs-render",
    "crates/obs-rs-render-wgpu",
    "crates/obs-rs-sandbox",
    "crates/obs-rs-ui",
    "crates/obs-rs-update",
    "crates/obs-rs-util",
    "crates/obs-rs-video",
]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.1.0"
publish = false

[profile.release]
codegen-units = 1
debug = 0
incremental = false
lto = "thin"
panic = "abort"
strip = "symbols"
