//! ABI probe for a Rust-authored OBS module.
//!
//! The required export signatures mirror `libobs/obs-module.h`:
//! `obs_module_load`, `obs_module_set_pointer`, and `obs_module_ver`. This crate is
//! an evaluation harness, not a production OBS plugin. It performs no registration
//! against libobs and returns API version `0` unless the build supplies
//! `OBS_LIBOBS_API_VER`, so an integration build must inject the version generated by
//! the target OBS checkout.

#![warn(clippy::all)]
#![warn(clippy::pedantic)]

use std::ffi::c_char;
use std::sync::atomic::{AtomicUsize, Ordering};

include!(concat!(env!("OUT_DIR"), "/api_version.rs"));

/// Opaque pointer type used by the native module ABI.
#[repr(C)]
pub struct ObsModule {
    _private: [u8; 0],
}

static MODULE_POINTER: AtomicUsize = AtomicUsize::new(0);
static MODULE_NAME: &[u8] = b"obs-rs-plugin-probe\0";
static MODULE_DESCRIPTION: &[u8] = b"Rust OBS module ABI probe\0";
static MODULE_AUTHOR: &[u8] = b"obs-rs migration workspace\0";

/// Required by the OBS module loader; this probe has no native registrations.
#[unsafe(no_mangle)]
pub extern "C" fn obs_module_load() -> bool {
    true
}

/// Required by the OBS module loader; records the opaque native module pointer.
///
/// # Safety
///
/// The pointer is treated as opaque and is never dereferenced. The caller must
/// provide the module pointer supplied by the native OBS loader or null.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn obs_module_set_pointer(module: *mut ObsModule) {
    MODULE_POINTER.store(module as usize, Ordering::Relaxed);
}

/// Required by the OBS module loader; returns the build-injected API version.
#[unsafe(no_mangle)]
pub extern "C" fn obs_module_ver() -> u32 {
    OBS_MODULE_API_VERSION
}

/// Optional module display name used by the ABI smoke test.
#[unsafe(no_mangle)]
pub extern "C" fn obs_module_name() -> *const c_char {
    MODULE_NAME.as_ptr().cast()
}

/// Optional module description used by the ABI smoke test.
#[unsafe(no_mangle)]
pub extern "C" fn obs_module_description() -> *const c_char {
    MODULE_DESCRIPTION.as_ptr().cast()
}

/// Optional module author string.
#[unsafe(no_mangle)]
pub extern "C" fn obs_module_author() -> *const c_char {
    MODULE_AUTHOR.as_ptr().cast()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn required_exports_have_probe_behavior() {
        let mut sentinel = 0_u8;
        // SAFETY: the probe treats this pointer as opaque and does not dereference it.
        unsafe { obs_module_set_pointer((&raw mut sentinel).cast()) };

        assert!(obs_module_load());
        assert_ne!(MODULE_POINTER.load(Ordering::Relaxed), 0);
        assert_eq!(obs_module_ver(), OBS_MODULE_API_VERSION);
        assert_eq!(obs_module_name(), MODULE_NAME.as_ptr().cast());
    }
}
